extends Node

signal language_changed(language_id: String)

const LANGUAGE_ENGLISH: String = "english"
const LANGUAGE_TAGALOG: String = "tagalog"
const SETTINGS_PATH: String = "user://language_settings.cfg"

const LANGUAGE_LABELS: Dictionary = {
	LANGUAGE_ENGLISH: "English",
	LANGUAGE_TAGALOG: "Tagalog",
}

const ENGLISH_TEXT: Dictionary = {
	"Anak, yung [b]bubong sa sala[/b]... [i]nag-aalala na ko dun.[/i]": "Son, the [b]living room roof[/b]... [i]I'm worried about it.[/i]",
	"Ano ba yan nak. naku": "Oh no, son.",
	"Nak, ikaw na mag-ayos ng [b]bubong[/b]. Salamat, nak.": "Son, please fix the [b]roof[/b]. Thank you.",
	"bakit po inay": "Why, Mother?",
	"ano ba naman yan ma jusq": "Oh no, Mom.",
	"Anak kamusta, Narinig mo na ba yung balita?": "Son, how are you? Have you heard the news?",
	"May paparating na bagyo ulit... kailangan nating maghanda.": "Another storm is coming... we need to prepare.",
	"Mas malakas daw ito kaysa dati, kaya kailangan nating maging maingat.": "They say this one is stronger than before, so we need to be careful.",
	"May kailangan tayong bilhin bago lumakas ang bagyo. Ito ang pera, anak.": "We need to buy supplies before the storm gets stronger. Here is the money, son.",
	"Pag may nakita kang kailangang ayusin sa bahay, bilhin mo agad ang kailangan.": "If you find anything in the house that needs fixing, buy what you need right away.",
	"[i]Inabot ni Nanay ang pera para sa mga kailangang bilhin.[/i] Hindi natin maililigtas lahat, anak. Unahin mo ang pinaka-kailangan.": "[i]Nanay handed over money for the supplies.[/i] We cannot save everything, son. Prioritize what matters most.",
	"Kasya dapat yan kung maingat ka sa pagbili. Mag-ingat ka ha.": "That should be enough if you buy carefully. Stay safe.",
	"Opo Nay. Hahanapin ko kung ano ang kailangan ihanda.": "Yes, Nay. I'll look for what needs to be prepared.",
	"Pasensya na anak, hindi ko kayang umalis ng bahay dahil wala mag aalaga sa bunso.": "I'm sorry, son. I cannot leave the house because no one else can watch your younger sibling.",
	"Ikaw lang maaasahan ko anak. Mag-ingat ka ha, bumalik ka agad.": "You're the only one I can count on, son. Be careful, and come back quickly.",
	"Ako na po bahala nay.": "I'll take care of it, Nay.",
	"Kamusta anak, nabili mo na ba ang mga kailangan?": "How are you, son? Did you buy what we need?",
	"Lumalakas na ang hangin anak, mag-ingat ka.": "The wind is getting stronger, son. Be careful.",
	"Huwag ka nang lumabas ulit anak. Malapit na ang bagyo, dito ka nalang at para ligtas.": "Do not go outside again, son. The storm is close. Stay here where it is safe.",
	"Oy apo, halika. Umupo ka muna sandali. ": "Come here, grandchild. Sit for a moment. ",
	"Apo yung bagyong paparating mag-ingat ka ha.": "The storm is coming, grandchild. Please be careful.",
	"Opo Lola.": "Yes, Lola.",
	"Mabuti naman. Pero yung [b]gamot[/b] ko huwag mo kalimutan yung sa [b]botika[/b] ha. ": "Good. But please do not forget my [b]medicine[/b] from the [b]pharmacy[/b]. ",
	"Pag walang gamot, mahihirapan ako. Pasensya na apo. ": "Without medicine, I will struggle. I'm sorry, grandchild. ",
	"Kailangan ni Lola ang [b]gamot[/b]. Kailangan ko pumunta ng [b]botika[/b].": "Lola needs [b]medicine[/b]. I need to go to the [b]pharmacy[/b].",
	"Sige na apo, pakilagay na lang sa [b]drawer sa higaan[/b] yung aking [b]gamot[/b]. ": "Alright, grandchild. Please put my [b]medicine[/b] in the [b]bedside drawer[/b]. ",
	"Yung [b]gamot[/b], huwag mong kalimutan apo. [i]Mahalaga yun sa akin.[/i]": "Please do not forget the [b]medicine[/b], grandchild. [i]It is important to me.[/i]",
	"Pag umulan nang malakas at walang [b]panakip sa kisame[/b]... [i]basa lahat tayo dito.[/i] ": "If the rain gets heavy and there is no [b]cover for the ceiling[/b]... [i]we will all get soaked in here.[/i] ",
	"Sabi ni Nanay, wala tayong [b]pagkain[/b] para bukas. Kailangan kahit [b]de lata[/b].": "Nanay said we have no [b]food[/b] for tomorrow. We need at least [b]canned goods[/b].",
	"Mabuti na. Nandito na tayo. Dasal lang tayo ngayon.": "Good. We are here now. All we can do is pray.",
	"Oh, iho, ano ang iyong mga kailangan?": "Oh, boy, what do you need?",
	"Pasensya na at nagtataas ako ng presyo, nagkakaubusan na kasi ngayon ng [b]supplies[/b].": "Sorry for raising prices. [b]Supplies[/b] are running out now.",
	"Ano ho yun?": "What is it?",
	"bibili po sana ako hehe... bukas po ba kayo?": "I was hoping to buy something... are you still open?",
	"Oo iho pili ka lang": "Yes, boy, just choose what you need.",
	"Bili na kayo, at magsasara na ako. Halos naubos na lahat ni Kapitan ang mga [b]supplies[/b].": "Buy now, because I am closing soon. The Captain has almost emptied all the [b]supplies[/b].",
	"Ikaw ulit?!!": "You again?!!",
	"Pero i-check mo sa una unahan baka ay mayroon pa tira-tirang [b]plywood[/b] doon.": "But check near the front. There might still be some leftover [b]plywood[/b] there.",
	"Oh, ano mga kailangan mo? Bilis, may bagyo na paparating at magsasara na ang [b]grocery[/b].": "What do you need? Hurry, a storm is coming and the [b]grocery[/b] will close soon.",
	"Ate Linda?? Nagtatrabaho karin pala sa hardware? Paano ka po nakarating dito?!": "Ate Linda?? You work at the hardware store too? How did you get here?!",
	"Sinong Ate Linda?! kita mo nag tatrabaho ako dito!": "Who is Ate Linda?! Can't you see I work here?",
	"Ano po ang inyong kailangan? Mabuti at naabutan niyo pa ang [b]botika[/b] na bukas.": "What do you need? Good thing you reached the [b]pharmacy[/b] while it is still open.",
	"Ano pa hinihintay mo iho, bili na ng aming malinamnam na manok!": "What are you waiting for, boy? Buy our delicious chicken!",
	"Siguradong mabubusog ka dito, promise!": "This will definitely fill you up, promise!",
	"VIC SOTTO?!?!": "VIC SOTTO?!?!",
	"hi hello heeello": "Hi, hello, hellooo.",
	"yes hola?": "Yes, hello?",
	"wala man hehe": "Nothing, hehe.",
	"Miss ko na kasi siya...": "I just miss them...",
	"Signal 3 na. Magiging Signal 4 sa loob ng sampung oras. Wala tayong panahon.": "It is Signal 3 now. It will become Signal 4 within ten hours. We do not have time.",
	"Kailangan ko muna ng supplies.": "I need supplies first.",
	"Pwede ko na to ayusin.": "I can fix this now.",
	"Naayos ko na ito.": "I fixed this.",
	"Hindi pa namin naayos yung nasirang [b]bubong[/b] noong nakaraang bagyo.": "We still have not fixed the [b]roof[/b] damaged by the last storm.",
	"[i]Mahirap ito kung hindi takpan.[/i]": "[i]This will be difficult if it is not covered.[/i]",
	"Kailangan ko ng [b]tarp[/b], [b]pako[/b], at [b]martilyo[/b] para maayos ito.": "I need a [b]tarp[/b], [b]nails[/b], and a [b]hammer[/b] to fix this.",
	"Naayos ko na ang bubong, mabuti naman at hindi na kami mababasa, sana kumapit ito.": "I fixed the roof. Good, we should not get wet now. I hope it holds.",
	"Lalakas ang hangin mamaya, kailangan ko [b]takpan ang bintana[/b].": "The wind will get stronger later. I need to [b]board up the window[/b].",
	"Lalakas ang hangin mamaya, kailangan ko [b]takpan itong bintana[/b].": "The wind will get stronger later. I need to [b]board up this window[/b].",
	"Kailangan ko ng [b]plywood[/b], [b]pako[/b], at [b]martilyo[/b]. Nasaan na kaya yung martilyo ni Papa?": "I need [b]plywood[/b], [b]nails[/b], and a [b]hammer[/b]. Where could Papa's hammer be?",
	"Kumpleto na mga kailangan ko, matatakpan ko na itong [b]bintana[/b].": "I have everything I need. I can board up this [b]window[/b] now.",
	"Natakpan ko na bintana, sana kumapit ito hanggang sa matapos ang bagyo.": "I boarded up the window. I hope it holds until the storm is over.",
	"Wala pa ring pagkain. Kailangan ng kahit [b]apat na de lata[/b] — para kay Nanay, Lola, Bunso, at ako.": "There is still no food. We need at least [b]four canned goods[/b] for Nanay, Lola, Bunso, and me.",
	"Unahin ko dapat ang [b]palengke[/b] kung kaya pa. Mas mura doon, pero mabilis magsara kapag tumaas ang baha.": "I should go to the [b]market[/b] first if I still can. It is cheaper there, but it closes quickly when the flood rises.",
	"Kung huli na ako, pwede pa kay [b]Ate Linda[/b] — mas mahal, pero mas malapit.": "If I am too late, I can still go to [b]Ate Linda[/b]. It is more expensive, but closer.",
	"Sapat na ito. Ilalagay ko na sa [b]ref[/b] para madali makuha kapag kailangan.": "This is enough. I will put it in the [b]fridge[/b] so it is easy to get when needed.",
	"Okay na ang pagkain. Hindi kami magugutom sa loob ng bagyo.": "The food is ready. We will not go hungry during the storm.",
	"Nako, nasira itong [b]lababo[/b] namin, kailangan ko ng [b]wrench[/b] para maayos ito.": "Oh no, our [b]sink[/b] is broken. I need a [b]wrench[/b] to fix it.",
	"Kailangan ko din ng [b]water jug[/b] para may tubig kami sa bagyo.": "I also need a [b]water jug[/b] so we have water during the storm.",
	"Maayos ko na ang [b]lababo[/b], pupunuin ko na rin ang [b]water jug[/b].": "I can fix the [b]sink[/b] now and fill the [b]water jug[/b].",
	"Maayos na lababo, nalagyan ko narin ang water jug ng tubig.": "The sink is fixed, and I filled the water jug.",
	"Yung [b]radyo[/b], nasaan na kaya...": "Where could the [b]radio[/b] be...",
	"Kailangan ko muna [b]ayusin ang radyo[/b] bago ko ito ilagay dito.": "I need to [b]fix the radio[/b] before I place it here.",
	"Maayos na itong [b]radyo[/b], ilalagay ko muna ito dito.": "The [b]radio[/b] works now. I will place it here.",
	"May radyo na kami, makakakuha na kami ng balita kahit may bagyo.": "We have a radio now. We can still get news during the storm.",
	"Yung [b]radyo[/b] at [b]flashlight[/b], nasaan na kaya...": "Where could the [b]radio[/b] and [b]flashlight[/b] be...",
	"Kailangan ko muna [b]ayusin ang radyo at flashlight[/b] para malagay ko dito.": "I need to [b]fix the radio and flashlight[/b] before placing them here.",
	"Maayos na itong [b]radyo[/b] at [b]flashlight[/b], ilalagay ko muna ito dito.": "The [b]radio[/b] and [b]flashlight[/b] work now. I will place them here.",
	"Mabuti din na may flashlight, baka biglang mawalan ng kuryente.": "It is good to have a flashlight too, in case the power goes out.",
	"Kailangan ko muna bumili sa [b]botika[/b] ng [b]gamot ni Lola[/b].": "I need to buy [b]Lola's medicine[/b] from the [b]pharmacy[/b] first.",
	"Nabili ko na yung [b]gamot[/b], mabuti naman.": "I bought the [b]medicine[/b]. Good.",
	"Meron na gamot si lola.": "Lola has medicine now.",
	"Mga lumang larawan namin...": "Our old photos...",
	"Kamusta na kaya si papa sa trabaho niya...": "I wonder how Papa is doing at work...",
	"Gas pa naman — pero pag nawalan ng kandila o flashlight, wag nating gamitin 'to sa dilim. Delikado.": "There is still gas, but if we lose candles or the flashlight, we should not use this in the dark. It is dangerous.",
	"Mahal na ang mga bilihin": "Goods are expensive now.",
	"Lahat ng ito order ni kap?": "The Captain ordered all of this?",
	"Hindi man lang siya nag tira para saaming taumbayan?": "He did not even leave any for the townspeople?",
	"Paubos na nga ang mga bilihin...": "The supplies are already running out...",
	"Buti naabutan ko pa na bukas itong hardware store.": "Good thing I reached this hardware store while it is still open.",
	"Pwede ko itong magamit sa [b]flashlight[/b] o [b]radyo[/b].": "I can use this for the [b]flashlight[/b] or [b]radio[/b].",
	"Kulang ito ng [b]baterya[/b]... [i]Sayang, makikinig pa naman sana ako.[/i]": "This needs a [b]battery[/b]... [i]Too bad, I was hoping to listen to it.[/i]",
	"Ayaw bumukas ng [b]flashlight[/b]...": "The [b]flashlight[/b] will not turn on...",
	"Siguro kailangan nito ng [b]baterya[/b].": "Maybe it needs a [b]battery[/b].",
	"Bagong [b]baterya[/b]. Pwede ito sa [b]flashlight[/b] o [b]radyo[/b].": "Fresh [b]batteries[/b]. These can be used for the [b]flashlight[/b] or [b]radio[/b].",
	"Yung [b]martilyo[/b] ni Tatay.": "Tatay's [b]hammer[/b].",
	"[i]Mabuti nandito pa.[/i]": "[i]Good, it is still here.[/i]",
	"Magagamit ko ito sa [b]bubong[/b] at [b]bintana[/b].": "I can use this on the [b]roof[/b] and [b]window[/b].",
	"Mga [b]pako[/b]...": "Some [b]nails[/b]...",
	"Kailangan ito sa [b]bubong[/b] at [b]bintana[/b].": "These are needed for the [b]roof[/b] and [b]window[/b].",
	"Tira-tirang [b]plywood[/b]. Magagamit ko ito sa [b]bintana[/b].": "Leftover [b]plywood[/b]. I can use this on the [b]window[/b].",
	"Mga [b]water jug[/b] — walang laman.": "Some [b]water jugs[/b], empty.",
	"Puwede ko itong punuin sa [b]gripo[/b].": "I can fill these at the [b]faucet[/b].",
	"[i]Libre pa.[/i]": "[i]And it is free.[/i]",
	"Gumagana na ang [b]radyo[/b]! Kailangan ko itong ilagay sa [b]shelf na katabi ni Lola[/b].": "The [b]radio[/b] works now! I need to place it on the [b]shelf beside Lola[/b].",
	"Banana": "Banana",
	"pagkain para kay Chris.": "Food for Chris.",
	"Batteries": "Batteries",
	"batteries..": "Batteries.",
	"Broken Radio": "Broken Radio",
	"Di nagana na radyo..": "A radio that no longer works.",
	"Canned Goods": "Canned Goods",
	"Pagkain para sa pamilya. 4 cans fit in one slot.": "Food for the family. 4 cans fit in one slot.",
	"Dead Flashlight": "Dead Flashlight",
	"Flashlight na walang baterya... lang kwenta pa": "A flashlight with no battery... it is useless for now.",
	"Fresh Batteries": "Fresh Batteries",
	"Fresh batteries": "Fresh batteries.",
	"hammer": "Hammer",
	"Yung martilyo ni Tatay. Mabuti nandito pa.": "Tatay's hammer. Good, it is still here.",
	"Medicine": "Medicine",
	"Medicine for lola": "Medicine for Lola.",
	"nails": "Nails",
	"pako": "Nails.",
	"plywood": "Plywood",
	"a piece of wood": "A piece of wood.",
	"Tarp": "Tarp",
	"Tarpulin": "Tarpaulin.",
	"Water Jugs": "Water Jugs",
	"water containers ": "Water containers.",
	"working_flashlight": "Working Flashlight",
	"May ilaw na woohoo": "It has light now.",
	"Working Radio": "Working Radio",
	"tugtugan na!": "It can play now!",
	"Wrench": "Wrench",
	"Whole Chicken": "Whole Chicken",
	"Malinamnam na manok ng Go To Chooks!": "Delicious chicken from Go To Chooks!",
	"Half Chicken": "Half Chicken",
	"Kalahati lang pero masarap parin, pramis": "Only half, but still tasty, promise.",
	"Ate Linda's Sari-sari": "Ate Linda's Sari-sari Store",
	"Medyo mahal ang presyo ng bilihin ngayon.": "Prices are a bit high right now.",
	"GroceryShop": "Grocery",
	"Mas mura ang bilihin dito, medyo malayo nga lang.": "Goods are cheaper here, but it is farther away.",
	"Hardware Store": "Hardware Store",
	"Ano kaya pwede ko bilihin para sa pagayos ng bahay.": "What can I buy to repair the house?",
	"PharmacyShop": "Pharmacy",
	"Dito ko lang makukuha yung gamot ni lola..": "This is the only place where I can get Lola's medicine.",
	"Go To Chooks": "Go To Chooks",
	"Masarap kahit walang chicken": "Still delicious, even without chicken.",
	"Home": "Home",
	"Ate Linda's": "Ate Linda's",
	"Botika": "Pharmacy",
	"Palengke": "Grocery / Market",
	"Nandito ka": "You are here",
	"Travel cost: ~%d min": "Travel cost: ~%d min",
	"  ⚠ Danger Zone": "  ⚠ Danger Zone",
	"  Closes early": "  Closes early",
	"STORM": "STORM",
	"STORM HAS ARRIVED": "STORM HAS ARRIVED",
	"Closed": "Closed",
	"Danger": "Danger",
	"No description.": "No description.",
	"Click an item to inspect.\nClick a second item to combine.": "Click an item to inspect.\nClick a second item to combine.",
	"These items can't be combined.": "These items can't be combined.",
	"Combine -> %s": "Combine -> %s",
	"Drag item to discard slot if you want to discard it.": "Drag item to discard slot if you want to discard it.",
	"Inventory": "Inventory",
	"Add this item to your backpack?": "Add this item to your backpack?",
	"Confident enough?": "Confident enough?",
	"Cash:  ₱": "Cash:  ₱",
	"Nabili! %s — nasa bag mo na.": "Bought! %s is now in your bag.",
	"Puno na ang bag mo. Mag-iwan muna ng item.": "Your bag is full. Leave an item first.",
	"Hindi sapat ang pera. Kulang ng ₱%d.": "Not enough money. You are short by ₱%d.",
	"Hindi nabili.": "Could not buy it.",
	"Pera: PHP %d": "Cash: PHP %d",
	"Preparation Checklist": "Preparation Checklist",
	"Patch the roof": "Patch the roof",
	"Tarp + nails + hammer": "Tarp + nails + hammer",
	"Get Lola's medicine": "Get Lola's medicine",
	"Pharmacy": "Pharmacy",
	"Store food": "Store food",
	"4x canned goods": "4x canned goods",
	"Fill water jugs": "Fill water jugs",
	"Home faucet": "Home faucet",
	"Board both windows": "Board both windows",
	"Plywood + nails + hammer": "Plywood + nails + hammer",
	"Assemble flashlight & radio": "Assemble flashlight & radio",
	"Flashlight + batteries; radio + batteries": "Flashlight + batteries; radio + batteries",
	"Talk to Nanay": "Talk to Nanay",
	"Talk to Lola": "Talk to Lola",
	"Explore around the house": "Explore around the house",
	"Bubong — leaking roof": "Roof — leaking roof",
	"Gamot ni Lola — medicine needed": "Lola's medicine — medicine needed",
	"Pagkain — fridge is empty": "Food — fridge is empty",
	"Bintana — weak second-floor windows": "Windows — weak second-floor windows",
	"Tubig — no filled water containers": "Water — no filled water containers",
	"Flashlight — dead batteries": "Flashlight — dead batteries",
	"%s remaining": "%s remaining",
	"Dumating ang Bagyo.": "The storm arrived.",
	"Nakaligtas kami lahat.": "We all survived.",
	"Nandito pa rin kami. Sugatan, pero buhay.": "We are still here. Wounded, but alive.",
	"Mahirap ang gabi. Pero hindi kami sumuko.": "The night was hard. But we did not give up.",
	"Hindi lahat ay naihanda. Hindi lahat ay napigilan.": "Not everything was prepared. Not everything was prevented.",
	"Matatag ang harang sa bintana, naligtas kami sa malalakas na hangin.": "The window barricade held strong, and we survived the heavy winds.",
	"Hindi natakpan ang dalawang bintana, kaya pinasok ng hangin at ulan ang bahay.": "The two windows were left uncovered, so wind and rain entered the house.",
	"Natakpan ang bubong sa oras, tuyo ang sahig at sala.": "The roof was covered in time, keeping the floor and living room dry.",
	"Hindi natakpan ang bubong, nabasa ang loob ng bahay.": "The roof was left uncovered, and the inside of the house got soaked.",
	"Mahimbing ang tulog ni Lola, sapat ang kanyang gamot.": "Lola slept peacefully. She had enough medicine.",
	"Hirap huminga si Lola, wala kaming naibigay na lunas.": "Lola struggled to breathe. We had no medicine to give her.",
	"May laman ang aming sikmura, may lakas kaming lumaban.": "We had food in our stomachs, and strength to keep going.",
	"Wala kaming nakain sa dumating na bagyo.": "We had nothing to eat when the storm came.",
	"May malinis kaming maiinom, ligtas kami sa uhaw.": "We had clean water to drink, safe from thirst.",
	"Tuyo ang lalamunan, madumi ang tubig sa paligid.": "Our throats were dry, surrounded by dirty floodwater.",
	"May liwanag at balita, alam namin ang nangyayari.": "We had light and news. We knew what was happening.",
	"Nabalot kami ng dilim, bingi kami sa labas ng mundo.": "Darkness surrounded us, cut off from the outside world.",
	"SAVE YOUR RUN": "SAVE YOUR RUN",
	"Mode: %s    Tasks: %d / %d    Time left: %s": "Mode: %s    Tasks: %d / %d    Time left: %s",
	"Enter player name": "Enter player name",
	"Every year, an average of 20 typhoons test our resilience. But while \"flood control projects\" remain sturdy only on paper and political tarpaulins, ordinary citizens are left to swim for their lives.": "Every year, an average of 20 typhoons test our resilience. But while \"flood control projects\" remain sturdy only on paper and political tarpaulins, ordinary citizens are left to swim for their lives.",
	"Safety is not a privilege to be earned. It is a basic accountability of those in power.": "Safety is not a privilege to be earned. It is a basic accountability of those in power.",
}

const TAGALOG_TEXT: Dictionary = {
	"Home": "Bahay",
	"Ate Linda's": "Kina Ate Linda",
	"Hardware Store": "Hardware Store",
	"Pharmacy": "Botika",
	"Grocery / Market": "Palengke",
	"Grocery": "Palengke",
	"You are here": "Nandito ka",
	"Travel cost: ~%d min": "Tagal ng byahe: ~%d min",
	"  ⚠ Danger Zone": "  ⚠ Delikadong lugar",
	"  Closes early": "  Maagang nagsasara",
	"STORM": "BAGYO",
	"STORM HAS ARRIVED": "DUMATING NA ANG BAGYO",
	"Closed": "Sarado",
	"Danger": "Delikado",
	"No description.": "Walang description.",
	"Click an item to inspect.\nClick a second item to combine.": "Pumili ng item para tingnan.\nPumili ng pangalawang item para pagsamahin.",
	"These items can't be combined.": "Hindi pwedeng pagsamahin ang mga item na ito.",
	"Combine -> %s": "Combine -> %s",
	"Drag item to discard slot if you want to discard it.": "I-drag ang item sa discard slot kung gusto mo itong itapon.",
	"Inventory": "Imbentaryo",
	"Add this item to your backpack?": "Idagdag ang item na ito sa bag mo?",
	"Confident enough?": "Handa ka na?",
	"Banana": "Saging",
	"pagkain para kay Chris.": "Pagkain para kay Chris.",
	"Batteries": "Baterya",
	"batteries..": "Baterya.",
	"Broken Radio": "Sirang Radyo",
	"Di nagana na radyo..": "Di na gumagana ang radyo.",
	"Canned Goods": "De Lata",
	"Pagkain para sa pamilya. 4 cans fit in one slot.": "Pagkain para sa pamilya. 4 na lata ang kasya sa isang slot.",
	"Dead Flashlight": "Sirang Flashlight",
	"Flashlight na walang baterya... lang kwenta pa": "Flashlight na walang baterya... wala pang kwenta.",
	"Fresh Batteries": "Bagong Baterya",
	"Fresh batteries": "Bagong baterya.",
	"hammer": "Martilyo",
	"Yung martilyo ni Tatay. Mabuti nandito pa.": "Yung martilyo ni Tatay. Mabuti nandito pa.",
	"Medicine": "Gamot",
	"Medicine for lola": "Gamot ni Lola.",
	"nails": "Pako",
	"pako": "Pako.",
	"plywood": "Plywood",
	"a piece of wood": "Isang pirasong kahoy.",
	"Tarp": "Tarp",
	"Tarpulin": "Tarpulin.",
	"Water Jugs": "Water Jugs",
	"water containers ": "Lalagyan ng tubig.",
	"working_flashlight": "Gumaganang Flashlight",
	"May ilaw na woohoo": "May ilaw na.",
	"Working Radio": "Gumaganang Radyo",
	"tugtugan na!": "Tugtugan na!",
	"Wrench": "Lyabe",
	"Whole Chicken": "Buong Manok",
	"Malinamnam na manok ng Go To Chooks!": "Malinamnam na manok ng Go To Chooks!",
	"Half Chicken": "Kalahating Manok",
	"Kalahati lang pero masarap parin, pramis": "Kalahati lang pero masarap pa rin, pramis.",
	"VIC SOTTO?!?!": "VIC SOTTO?!?!",
	"hi hello heeello": "Hi, hello, hellooo.",
	"yes hola?": "Yes, hello?",
	"wala man hehe": "Wala naman, hehe.",
	"Miss ko na kasi siya...": "Miss ko na kasi siya...",
	"Ate Linda's Sari-sari": "Sari-sari Store ni Ate Linda",
	"Medyo mahal ang presyo ng bilihin ngayon.": "Medyo mahal ang presyo ng bilihin ngayon.",
	"GroceryShop": "Palengke",
	"Mas mura ang bilihin dito, medyo malayo nga lang.": "Mas mura ang bilihin dito, medyo malayo nga lang.",
	"Ano kaya pwede ko bilihin para sa pagayos ng bahay.": "Ano kaya ang pwede kong bilhin para sa pag-aayos ng bahay?",
	"PharmacyShop": "Botika",
	"Dito ko lang makukuha yung gamot ni lola..": "Dito ko lang makukuha yung gamot ni Lola.",
	"Go To Chooks": "Go To Chooks",
	"Masarap kahit walang chicken": "Masarap kahit walang chicken.",
	"Cash:  ₱": "Pera:  ₱",
	"Bought! %s is now in your bag.": "Nabili! %s — nasa bag mo na.",
	"Your bag is full. Leave an item first.": "Puno na ang bag mo. Mag-iwan muna ng item.",
	"Not enough money. You are short by ₱%d.": "Hindi sapat ang pera. Kulang ng ₱%d.",
	"Could not buy it.": "Hindi nabili.",
	"Cash: PHP %d": "Pera: PHP %d",
	"Preparation Checklist": "Listahan ng Paghahanda",
	"Patch the roof": "Takpan ang bubong",
	"Tarp + nails + hammer": "Tarp + pako + martilyo",
	"Get Lola's medicine": "Kunin ang gamot ni Lola",
	"Store food": "Mag-imbak ng pagkain",
	"4x canned goods": "4x de lata",
	"Fill water jugs": "Punuin ang water jugs",
	"Home faucet": "Gripo sa bahay",
	"Board both windows": "Takpan ang dalawang bintana",
	"Plywood + nails + hammer": "Plywood + pako + martilyo",
	"Assemble flashlight & radio": "Ayusin ang flashlight at radyo",
	"Flashlight + batteries; radio + batteries": "Flashlight + baterya; radyo + baterya",
	"Talk to Nanay": "Kausapin si Nanay",
	"Talk to Lola": "Kausapin si Lola",
	"Explore around the house": "Maglibot sa bahay",
	"Roof — leaking roof": "Bubong — leaking roof",
	"Lola's medicine — medicine needed": "Gamot ni Lola — medicine needed",
	"Food — fridge is empty": "Pagkain — fridge is empty",
	"Windows — weak second-floor windows": "Bintana — weak second-floor windows",
	"Water — no filled water containers": "Tubig — no filled water containers",
	"%s remaining": "%s ang natitira",
	"The storm arrived.": "Dumating ang Bagyo.",
	"We all survived.": "Nakaligtas kami lahat.",
	"We are still here. Wounded, but alive.": "Nandito pa rin kami. Sugatan, pero buhay.",
	"The night was hard. But we did not give up.": "Mahirap ang gabi. Pero hindi kami sumuko.",
	"Not everything was prepared. Not everything was prevented.": "Hindi lahat ay naihanda. Hindi lahat ay napigilan.",
	"The window barricade held strong, and we survived the heavy winds.": "Matatag ang harang sa bintana, naligtas kami sa malalakas na hangin.",
	"The two windows were left uncovered, so wind and rain entered the house.": "Hindi natakpan ang dalawang bintana, kaya pinasok ng hangin at ulan ang bahay.",
	"The roof was covered in time, keeping the floor and living room dry.": "Natakpan ang bubong sa oras, tuyo ang sahig at sala.",
	"The roof was left uncovered, and the inside of the house got soaked.": "Hindi natakpan ang bubong, nabasa ang loob ng bahay.",
	"Lola slept peacefully. She had enough medicine.": "Mahimbing ang tulog ni Lola, sapat ang kanyang gamot.",
	"Lola struggled to breathe. We had no medicine to give her.": "Hirap huminga si Lola, wala kaming naibigay na lunas.",
	"We had food in our stomachs, and strength to keep going.": "May laman ang aming sikmura, may lakas kaming lumaban.",
	"We had nothing to eat when the storm came.": "Wala kaming nakain sa dumating na bagyo.",
	"We had clean water to drink, safe from thirst.": "May malinis kaming maiinom, ligtas kami sa uhaw.",
	"Our throats were dry, surrounded by dirty floodwater.": "Tuyo ang lalamunan, madumi ang tubig sa paligid.",
	"We had light and news. We knew what was happening.": "May liwanag at balita, alam namin ang nangyayari.",
	"Darkness surrounded us, cut off from the outside world.": "Nabalot kami ng dilim, bingi kami sa labas ng mundo.",
	"SAVE YOUR RUN": "I-SAVE ANG RUN",
	"Mode: %s    Tasks: %d / %d    Time left: %s": "Mode: %s    Gawain: %d / %d    Natitirang oras: %s",
	"Enter player name": "Ilagay ang pangalan ng player",
	"Every year, an average of 20 typhoons test our resilience. But while \"flood control projects\" remain sturdy only on paper and political tarpaulins, ordinary citizens are left to swim for their lives.": "Taon-taon, humigit-kumulang 20 bagyo ang sumusubok sa ating tatag. Pero habang ang mga \"flood control project\" ay matibay lang sa papel at political tarpaulin, ordinaryong mamamayan ang naiiwang lumangoy para mabuhay.",
	"Safety is not a privilege to be earned. It is a basic accountability of those in power.": "Ang kaligtasan ay hindi pribilehiyong kailangang paghirapan. Ito ay pangunahing pananagutan ng mga nasa kapangyarihan.",
}

var current_language: String = LANGUAGE_ENGLISH

func _ready() -> void:
	_load_settings()

func set_language(language_id: String) -> void:
	if not LANGUAGE_LABELS.has(language_id):
		language_id = LANGUAGE_ENGLISH
	if current_language == language_id:
		return
	current_language = language_id
	_save_settings()
	language_changed.emit(current_language)

func get_language() -> String:
	return current_language

func get_language_index() -> int:
	return 1 if current_language == LANGUAGE_TAGALOG else 0

func get_language_from_index(index: int) -> String:
	return LANGUAGE_TAGALOG if index == 1 else LANGUAGE_ENGLISH

func translate(text: String) -> String:
	if text.is_empty():
		return text
	if current_language == LANGUAGE_TAGALOG:
		return TAGALOG_TEXT.get(text, text)
	return ENGLISH_TEXT.get(text, text)

func trf(text: String, values: Array) -> String:
	return translate(text) % values

func _load_settings() -> void:
	var config := ConfigFile.new()
	if config.load(SETTINGS_PATH) != OK:
		current_language = LANGUAGE_ENGLISH
		return
	current_language = str(config.get_value("language", "current", LANGUAGE_ENGLISH))
	if not LANGUAGE_LABELS.has(current_language):
		current_language = LANGUAGE_ENGLISH

func _save_settings() -> void:
	var config := ConfigFile.new()
	config.set_value("language", "current", current_language)
	config.save(SETTINGS_PATH)
